branches: 
  only: 
    - master
    - develop
jdk: oraclejdk7
language: java
install: true
script: mvn clean cobertura:check | egrep -v "(^\[INFO\]|^\[DEBUG\])"
after_success:
  - bash "deploy.sh"
addons:
  ssh_known_hosts: tptacsutnfrba-pablogallazzi.rhcloud.com
notifications:
  email:
    recipients:
      - pablogallazzi@gmail.com
      - nicolas.g.garcia1@gmail.com
    on_success: never
    on_failure: always
