branches: 
  only: 
    - master
    - develop
jdk: oraclejdk8
language: java
install: true
script: mvn clean jacoco:prepare-agent install jacoco:report | egrep -v "(^\[INFO\]|^\[DEBUG\])"
notifications:
  email:
    recipients:
      - pablogallazzi@gmail.com
    on_success: never
    on_failure: always
after_success:
- bash <(curl -s https://codecov.io/bash)