branches: 
  only: 
    - master
    - develop
jdk: oraclejdk8
language: java
install: true
script: mvn clean cobertura:check | egrep -v "(^\[INFO\]|^\[DEBUG\])"
notifications:
  email:
    recipients:
      - pablogallazzi@gmail.com
    on_success: never
    on_failure: always
